# Generated by Django 4.1.4 on 2022-12-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_photo_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.TextField(default='No Image'),
        ),
    ]
